version: "3.8"
services:
  database:
    image: postgres
    restart: unless-stopped
    hostname: postgresql
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - data:/var/lib/postgresql/data
  api:
    build: .
    env_file:
      - .env
    ports:
      - "4000:4000"
    networks:
      - postgres
    depends_on:
      - database
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  data:
networks:
  postgres:
    driver: bridge